version: 0.2
phases:
  install:
    commands:
      - pip install yq
  pre_build:
    commands:
      - echo "Starting CliXX deployment"
      - echo "more commands"
  build:
    on-failure: ABORT
    commands:
      - echo starting build on `date`
      - echo "Creating CliXX Security Group for apps and database"
      - |
          import boto3

          sts_client=boto3.client('sts')

          #Calling the assume_role function
          assumed_role_object=sts_client.assume_role(RoleArn='arn:aws:iam::495599767034:role/Engineer', RoleSessionName='mysession')

          credentials=assumed_role_object['Credentials']

          print(credentials)

          s3=boto3.client('s3',aws_access_key_id=credentials['AccessKeyId'],aws_secret_access_key=credentials['SecretAccessKey'],aws_session_token=credentials['SessionToken'])
          response = s3.list_buckets(
          MaxBuckets=123)

          print(response)
      - |
         aws ec2 create-security-group \
         --group-name demo-sg \
         --description "AWS ec2 CLI Demo SG" \
         --tag-specifications 'ResourceType=security-group,Tags=[{Key=Name,Value=demo-sg}]' \
         --vpc-id "vpc-0c6460b8c3c8fe62f" \
         --region "us-east-1"
  post_build:
    commands:
      - echo Build completed on `date`