version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Starting CliXX deployment"
      - echo "more commands"
  build:
    on-failure: ABORT
    commands:
      - echo starting build on `date`
      - echo "Creating CliXX Security Group for apps and database"
      - python assume_role.py
      - |
         aws ec2 create-security-group \
         --group-name demo-sg \
         --description "AWS ec2 CLI Demo SG" \
         --tag-specifications 'ResourceType=security-group,Tags=[{Key=Name,Value=demo-sg}]' \
         --vpc-id "vpc-0c6460b8c3c8fe62f" \
         --region "us-east-1"
  post_build:
    commands:
      - echo Build completed on `date`